version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./tmp:/home/node/app/tmp
      - ./package.json:/home/node/app/package.json
      - ./package-lock.json:/home/node/app/package-lock.json
    container_name: reserva-bp
    expose:
      - "3333"
    ports:
      - "3333:3333"
    env_file:
      - ./.env
    command: sh -c "npm run dev"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mongo-test:
    image: mongo
    container_name: mongo-test-db
    restart: "no"
    ports:
      - "27018:27017"
    volumes:
      - ./data-test:/data/db
